7name: ETL Pipeline CI/CD
on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      -  name : print current directory
         run: pwd && ls
      - name: Set up Docker
        run: |
          docker --version
          docker-compose --version

      - name: Start Services with Docker Compose
        run: docker-compose up -d

      # Add a delay to ensure services are ready
      - name: Wait for Services to Initialize
        run: sleep 30

      - name: Verify Hive Data
        # Remove -it flag and use the correct container name
        run: |
          docker exec metastore beeline -u "jdbc:hiveserver2://localhost:10000" -e "SHOW TABLES;"

      - name: Stop Docker Containers
        run: docker-compose down
